// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/maiaaraujo5/controle_de_transacao/internal/app/controle_de_transacao/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// Transaction is an autogenerated mock type for the Transaction type
type Transaction struct {
	mock.Mock
}

// Find provides a mock function with given fields: parentContext, transactionID
func (_m *Transaction) Find(parentContext context.Context, transactionID string) (*model.Transaction, error) {
	ret := _m.Called(parentContext, transactionID)

	var r0 *model.Transaction
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Transaction); ok {
		r0 = rf(parentContext, transactionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(parentContext, transactionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: parentContext, transaction
func (_m *Transaction) Save(parentContext context.Context, transaction *model.Transaction) (*model.Transaction, error) {
	ret := _m.Called(parentContext, transaction)

	var r0 *model.Transaction
	if rf, ok := ret.Get(0).(func(context.Context, *model.Transaction) *model.Transaction); ok {
		r0 = rf(parentContext, transaction)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *model.Transaction) error); ok {
		r1 = rf(parentContext, transaction)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
