// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/maiaaraujo5/controle_de_transacao/internal/app/controle_de_transacao/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// CreateAccount is an autogenerated mock type for the CreateAccount type
type CreateAccount struct {
	mock.Mock
}

// Execute provides a mock function with given fields: parentContext, account
func (_m *CreateAccount) Execute(parentContext context.Context, account *model.Account) (*model.Account, error) {
	ret := _m.Called(parentContext, account)

	var r0 *model.Account
	if rf, ok := ret.Get(0).(func(context.Context, *model.Account) *model.Account); ok {
		r0 = rf(parentContext, account)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Account)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *model.Account) error); ok {
		r1 = rf(parentContext, account)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
