// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/maiaaraujo5/controle_de_transacao/internal/app/controle_de_transacao/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// RecoverTransaction is an autogenerated mock type for the RecoverTransaction type
type RecoverTransaction struct {
	mock.Mock
}

// Execute provides a mock function with given fields: parentContext, transactionID
func (_m *RecoverTransaction) Execute(parentContext context.Context, transactionID string) (*model.Transaction, error) {
	ret := _m.Called(parentContext, transactionID)

	var r0 *model.Transaction
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Transaction); ok {
		r0 = rf(parentContext, transactionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(parentContext, transactionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
