swagger: '2.0'
info:
  version: '1.0'
  title: Controle de Transação
  contact: {}
host: localhost:8080
basePath: /
securityDefinitions: {}
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /accounts:
    post:
      summary: Create Account
      tags:
      - Accounts
      operationId: CreateAccount
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/CreateAccountRequest'
      responses:
        201:
          description: 'successful operation'
          schema: 
             $ref: '#/definitions/AccountResponse'
          headers: {}
        400:
          description: 'bad request'
          schema:
            $ref: '#/definitions/BadRequestResponse'
        409:
          description: 'conflict'
          schema:
            $ref: '#/definitions/ConflictResponse'
        
        500:
          description: 'internal server error'
          schema:
            $ref: '#/definitions/InternalServerErrorResponse'
  /accounts/{accountId}:
    get:
      summary: Recover Account
      tags:
      - Accounts
      operationId: RecoverAccount
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: accountId
        in: path
        description: ID of account to return
        required: true
        type: integer
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: 'successful operation'
          schema: 
             $ref: '#/definitions/AccountResponse'
          headers: {}
        404:
          description: 'not found'
          schema:
            $ref: '#/definitions/NotFoundResponse'
        
        500:
          description: 'internal server error'
          schema:
            $ref: '#/definitions/InternalServerErrorResponse'
  /transactions:
    post:
      summary: Create Transaction
      tags:
      - Transactions
      operationId: CreateTransaction
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/CreateTransactionRequest'
      responses:
        201:
          description: 'successful operation'
          schema:
            $ref: '#/definitions/TransactionResponse'
          headers: {}
        400:
          description: 'bad request'
          schema:
            $ref: '#/definitions/BadRequestResponse'
        404:
          description: 'account not found'
          schema:
            $ref: '#/definitions/NotFoundResponse'
        
        500:
          description: 'internal server error'
          schema:
            $ref: '#/definitions/InternalServerErrorResponse'
          
        
  /transactions/{transactionId}:
    get:
      summary: Recover Transaction
      tags:
      - Transactions
      operationId: RecoverTransaction
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: transactionId
        in: path
        description: ID of transaction to return
        required: true
        type: integer
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: 'successful operation'
          schema:
            $ref: '#/definitions/TransactionResponse'
          headers: {}
        400:
          description: 'bad request'
          schema:
            $ref: '#/definitions/BadRequestResponse'
        404:
          description: 'transaction not found'
          schema:
            $ref: '#/definitions/NotFoundResponse'
        
        500:
          description: 'internal server error'
          schema:
            $ref: '#/definitions/InternalServerErrorResponse'
definitions:
  CreateAccountRequest:
    title: CreateAccountRequest
    example:
      document_number: "1234568989"
    type: object
    properties:
      document_number:
        type: string
    required:
    - document_number
  CreateTransactionRequest:
    title: CreateTransactionRequest
    example:
      account_id: 1
      operation_type_id: 1
      amount: 126.85
    type: object
    properties:
      account_id:
        type: integer
        format: int32
      operation_type_id:
        type: integer
        format: int32
      amount:
        type: number
        format: double
    required:
    - account_id
    - operation_type_id
    - amount
  AccountResponse:
    title: AccountResponse
    example: 
      account_id: 1
      document_number: "1234568989"
    type: object
    properties:
      account_id:
        type: integer
        format: int32
      document_number:
        type: string
  TransactionResponse:
    title: TransactionResponse
    example:
      id: 1
      account_id: 1
      operation_type_id: 1
      amount: 126.85
      event_date: "2020-11-20T16:45:59.396274Z"
    type: object
    properties:
      id:
        type: integer
        format: int32
      account_id:
        type: integer
        format: int32
      operation_type_id:
        type: integer
        format: int32
      event_date:
        type: string
  InternalServerErrorResponse:
    title: InternalServerErrorResponse
    example: 
      status_code: 500
      message: "internal server error"
    type: object
    properties:
      status_code:
        type: integer
        format: int32
      message:
        type: string
  NotFoundResponse:
    title: InternalServerErrorResponse
    example: 
      status_code: 404
      message: "not found"
    type: object
    properties:
      status_code:
        type: integer
        format: int32
      message:
        type: string
  BadRequestResponse:
    title: InternalServerErrorResponse
    example: 
      status_code: 400
      message: "bad request"
    type: object
    properties:
      status_code:
        type: integer
        format: int32
      message:
        type: string
  ConflictResponse:
    title: InternalServerErrorResponse
    example: 
      status_code: 409
      message: "conflict"
    type: object
    properties:
      status_code:
        type: integer
        format: int32
      message:
        type: string
  
  
tags:
- name: Accounts
  description: ''
- name: Transactions
  description: ''